version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Console d'administration graphique MinIO
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

